# Generated by Django 4.2.3 on 2023-07-12 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="head_image",
            field=models.ImageField(upload_to="posts/static/fotos"),
        ),
    ]
