# Generated by Django 4.2.3 on 2023-07-12 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0003_alter_post_head_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="head_image",
            field=models.ImageField(upload_to="fotos"),
        ),
    ]
